version: 2
jobs:
  build:
    working_directory: ~/dylan
    docker:
      - image: bitwalker/alpine-elixir:1.4.5
    environment:
      - MIX_ENV: test
    steps:

      # Clone project
      - checkout

      # Install deps
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

      # Compile
      - run: mix compile --warnings-as-errors

      # Test
      - run: mix test --trace # TODO: use coveralls
